<Project>
  <PropertyGroup>
    <!-- Enable central package management, https://learn.microsoft.com/en-us/nuget/consume-packages/Central-Package-Management -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
    <CentralPackageFloatingVersionsEnabled>true</CentralPackageFloatingVersionsEnabled>
  </PropertyGroup>
  
  <ItemGroup>
    <PackageVersion Include="System.Text.Json" Version="10.0.10" />
    <PackageVersion Include="System.Configuration.ConfigurationManager" Version="10.0.10" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.19.2" />
    <PackageVersion Include="System.Runtime" Version="4.3.1" />
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Caching.Memory" Version="10.0.10" />    
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.10"/>
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="10.0.10"/>
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.10"/>
    <PackageVersion Include="Microsoft.Extensions.Logging.Configuration" Version="10.0.10"/>
    <PackageVersion Include="Microsoft.Extensions.Logging.Debug" Version="10.0.10"/>
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.10" />    
  </ItemGroup>

  <ItemGroup>
    <PackageVersion Include="Microsoft.SourceLink.GitHub" Version="10.0.301" PrivateAssets="All" />
    <PackageVersion Include="Microsoft.Identity.Client" Version="4.86.1" />    
  </ItemGroup>


  <ItemGroup Condition="$(TargetFramework.StartsWith('netstandard2.0'))">
    <PackageVersion Include="Microsoft.Bcl.AsyncInterfaces" Version="10.0.10" />
  </ItemGroup>  
  

  <ItemGroup>
    <PackageVersion Include="Microsoft.ApplicationInsights" Version="2.23.0" />    
    <PackageVersion Include="AngleSharp" Version="0.17.0" />
    <!--<PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.0-*" PrivateAssets="All" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />-->
    <PackageVersion Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.*" PrivateAssets="All" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
    <PackageVersion Include="TimeZoneConverter" Version="7.2.0" />
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
  </ItemGroup>

  <!-- For managing the version of the SDK project 'MSTest.Sdk' use the global.json file.-->
  <!--<ItemGroup>
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.11.1" />
    <PackageVersion Include="MSTest.TestAdapter" Version="3.6.3" />
    <PackageVersion Include="MSTest.TestFramework" Version="3.6.3" />
    <PackageVersion Include="coverlet.collector" Version="6.0.0" PrivateAssets="All" IncludeAssets="runtime; build; native; contentfiles; analyzers; buildtransitive" />
  </ItemGroup>-->

  
</Project>
